GET http://localhost:8080/api/auth/who-am-i
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1dmVyYUBnaXRodWIuaW8iLCJpYXQiOjE2MzQzMTQxMjEsImV4cCI6MTYzNDQwMDUyMX0.vMFgQw4YO_wOCdsC7N5R5wCoKuOiM3oiWErJeYNcujFpJAVhdX33GT0aoWeh5ZivELtNh2OD1B847xfg-23HbQ
