spring:
  data:
    mongodb:
      repositories:
        type: auto
      uri: mongodb://127.0.0.1:27017
      database: 'spring-reactive-mongodb'
      auto-index-creation: true

spring-helmet:
  reactive:
    enable-cross-origin-embedder-policy: true
    enable-cross-origin-opener-policy: true
    enable-cross-origin-resource-policy: true
    enable-origin-agent-cluster: true
    enable-referrer-policy: true
    enable-strict-transport-security: true
    enable-do-not-sniff-mimetype: true
    enable-x-dns-prefetch-control: true
    enable-x-download-options: true
    enable-x-frame-options: true
    enable-x-permitted-cross-domain-policies: true
    remove-x-powered-by: true
    disable-x-xss-protection: true
    enable-content-security-policy: true

app:
  jwt:
    token:
      access:
        secret: "XCidHS4OsejNKlztvyWUgbQMtne8ZJlePZXBsa6tUUiMeJ+RZ1Y+6g7oyuoIP3eIl3hWHu+jic77N+GeDzavF0yN2h/YeY0051zgs0DfqfwKsmbiEfrDfkTpVLqEGPB4teLLh203//GG5OT0GystG6xvuVWwoaDALz5Ncjy7BhY="
        expiration-in-minutes: 1440
      refresh:
        secret: "Yv062gWWBJ2yP0nxw4X3D0RKjx8lwCG/jLgqbocJJM8aa65O72X11dEfVj3SnI/xX7PmdfEBUmOVI1uUCFAg4FqgFUwvEtQhCo5lGGQTIpg8oLzojXAM2zXVwm2IcJAaFlZnkOwyftjefEomyuqUSwiJvYa4vbrUMSC7DhNRBCM="
        expiration-in-minutes: 44640
